import assert from "node:assert/strict";
import test from "node:test";
import { FORWARD_EVALUATION_VAULT_SCHEMA_VERSION as V, classifyForwardVaultAppend, forwardVaultDigest, canPoolStages, resultMatchesProtocol, validateForwardVaultRecord, type Membership, type EvaluationProtocol, type EvaluationResult } from "./forwardEvaluationVault";
const d=(c:string)=>c.repeat(64);
const membership=():Membership=>({schemaVersion:V,kind:"MEMBERSHIP",recordId:"member:1",evidenceStage:"SHADOW_FORWARD",createdAt:"2026-09-24T10:00:00Z",cohortId:"cohort:1",enrollmentProtocolId:"enroll:1",enrollmentProtocolDigest:d("a"),canonicalRaceId:"fixture-race-1",decisionRecordId:"decision:1",decisionRecordDigest:d("b"),enrolledAt:"2026-09-24T10:00:00Z",included:true,reason:"prospective rule matched"});
const protocol=():EvaluationProtocol=>({schemaVersion:V,kind:"EVALUATION_PROTOCOL",recordId:"eval-protocol:1",evidenceStage:"SHADOW_FORWARD",createdAt:"2026-09-24T09:00:00Z",evaluationProtocolId:"eval:1",comparisonMode:"COMMON_COHORT",oddsBasis:"BUY_TIME",metricFamilies:["ROI"],unresolvedPolicy:"EXCLUDE_AND_COUNT",benchmarkDecisionSystems:["CURRENT_BUY"],protocolVersion:"v1"});
const result=(p=protocol()):EvaluationResult=>({schemaVersion:V,kind:"RESULT",recordId:"result:1",evidenceStage:"SHADOW_FORWARD",createdAt:"2026-09-24T11:00:00Z",resultId:"result:1",analysisSnapshotId:"snapshot:1",analysisSnapshotDigest:d("c"),evaluationProtocolId:p.evaluationProtocolId,evaluationProtocolDigest:forwardVaultDigest(p),decisionSystem:"research-fixture",comparisonMode:p.comparisonMode,oddsBasis:p.oddsBasis,metricFamily:"ROI",includedCount:1,excludedCount:0,metrics:{roi:1.2},sourceManifestDigest:d("d"),evaluatorVersion:"fixture-v1"});

test("membership is strict and outcome fields cannot mutate enrollment",()=>{ const m=membership(); assert.deepEqual(validateForwardVaultRecord(m),{valid:true,errors:[]}); const hindsight={...m,payoutYen:999}; const v=validateForwardVaultRecord(hindsight); assert.equal(v.valid,false); assert.ok(v.errors.includes("unknown field is not allowed: payoutYen")); });
test("canonical digest and append boundary are idempotent/fail-closed",()=>{ const m=membership(); assert.equal(classifyForwardVaultAppend(undefined,m),"APPEND"); assert.equal(classifyForwardVaultAppend(m,{...m}),"IDEMPOTENT_NOOP"); assert.equal(classifyForwardVaultAppend(m,{...m,reason:"changed after outcome"}),"CONFLICT"); assert.match(forwardVaultDigest(m),/^[0-9a-f]{64}$/); });
test("evidence stages cannot be pooled",()=>{ assert.equal(canPoolStages(["SHADOW_FORWARD","SHADOW_FORWARD"]),true); assert.equal(canPoolStages(["HISTORICAL","SHADOW_FORWARD"]),false); assert.equal(canPoolStages(["VALIDATION","UNTOUCHED_HOLDOUT"]),false); });
test("result must preserve frozen protocol stage, denominator mode and odds basis",()=>{ const p=protocol(), r=result(p); assert.equal(resultMatchesProtocol(r,p),true); assert.equal(resultMatchesProtocol({...r,comparisonMode:"SELECTED_RACE"},p),false); assert.equal(resultMatchesProtocol({...r,oddsBasis:"CLOSING"},p),false); assert.equal(resultMatchesProtocol({...r,evidenceStage:"HISTORICAL"},p),false); });
test("unsafe counts, unknown fields and non-finite metrics fail closed",()=>{ const r=result(); assert.equal(validateForwardVaultRecord({...r,includedCount:Number.MAX_SAFE_INTEGER+1}).valid,false); assert.equal(validateForwardVaultRecord({...r,metrics:{roi:Infinity}}).valid,false); assert.equal(validateForwardVaultRecord({...r,productionConnection:true}).valid,false); });
