/** 他場締切の集中による投票者attention分散とexacta市場残差を調べるread-only screen。 */
import { mkdirSync, writeFileSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import { attentionContext, isCompleteVenueDay, type ScheduledRace } from "../src/domain/marketAttention";

type ProgramRow={race_id:string;date:string;venue:string;race_no:number;close_at:string};type OddsRow={race_id:string;date:string;combination:string;odds:number;winner:string|null;payout_yen:number|null};type Metric={n:number;hits:number;edgePp:number;roi:number;max2HitExclRoi:number};type EvalRow={period:"discovery"|"forward";date:string;venue:string;raceNo:number;selection:string;implied:number;hit:boolean;payout:number;flags:string[]};
const selections=["1-2","1-3","1-4","1-5","1-6"];
const factors=[
  ["collision_2m","他場締切が前後2分以内","collision"],["multi_collision_5m","他場締切が前後5分以内に2本以上","collision"],["isolated_10m","他場締切まで10分以上孤立","collision"],
  ["same_round_5m","同じR番号の他場締切が前後5分以内","round"],["finals_cluster","10R以降かつ前後5分に他場2本以上","round"],
  ["busy_15venues","同日15場以上開催","load"],["light_10venues","同日10場以下開催","load"],["morning_before12","正午前締切","time"],["evening_after17","17時以降締切","time"],
  ["minute_0or5_placebo","締切分末尾0・5_placebo","placebo"],["minute_7_placebo","締切分末尾7_placebo","placebo"],
] as const;
const db=new DatabaseSync(process.env.BOAT_PON_DB_PATH??"data/boat.sqlite",{readOnly:true});db.exec("PRAGMA query_only=ON; PRAGMA busy_timeout=30000;");
try{
  const programs=db.prepare("SELECT race_id,date,venue,race_no,close_at FROM official_programs WHERE date BETWEEN '2024-01-01' AND '2025-12-31'").all() as ProgramRow[];
  const venueDays=new Map<string,ProgramRow[]>();for(const row of programs){const key=`${row.date}|${row.venue}`,group=venueDays.get(key)??[];group.push(row);venueDays.set(key,group);}
  const validPrograms=programs.filter(row=>isCompleteVenueDay((venueDays.get(`${row.date}|${row.venue}`)??[]).map(schedule)));
  const byDate=new Map<string,ScheduledRace[]>(),programByRace=new Map<string,ProgramRow>();for(const row of validPrograms){const group=byDate.get(row.date)??[];group.push(schedule(row));byDate.set(row.date,group);programByRace.set(row.race_id,row);}
  const odds=db.prepare(`SELECT h.race_id,h.race_date AS date,h.combination,h.odds,p.combination AS winner,p.payout_yen FROM historical_alternative_odds h LEFT JOIN race_payouts p ON p.race_id=h.race_id AND p.bet_type='exacta' WHERE h.bet_type='exacta' AND h.race_date BETWEEN '2024-01-01' AND '2025-12-31' AND h.combination IN('1-2','1-3','1-4','1-5','1-6') AND NOT EXISTS(SELECT 1 FROM race_entries re WHERE re.race_id=h.race_id AND re.status_code='F') AND (SELECT COUNT(*) FROM historical_alternative_odds a WHERE a.race_id=h.race_id AND a.bet_type='exacta')=30`).all() as OddsRow[];
  const overround=new Map((db.prepare("SELECT race_id,SUM(1.0/odds) value FROM historical_alternative_odds WHERE bet_type='exacta' AND race_date BETWEEN '2024-01-01' AND '2025-12-31' GROUP BY race_id HAVING COUNT(*)=30").all() as Array<{race_id:string;value:number}>).map(r=>[r.race_id,r.value]));
  const evalRows:EvalRow[]=[];let scheduledRaces=0;for(const row of odds){const program=programByRace.get(row.race_id);if(!program)continue;const context=attentionContext(schedule(program),byDate.get(row.date)??[]);if(!context)continue;scheduledRaces+=row.combination===selections[0]?1:0;const flags:string[]=[];if(context.otherWithin2>=1)flags.push("collision_2m");if(context.otherWithin5>=2)flags.push("multi_collision_5m");if((context.nearestOtherMinutes??0)>=10)flags.push("isolated_10m");if(context.sameRoundWithin5)flags.push("same_round_5m");if(program.race_no>=10&&context.otherWithin5>=2)flags.push("finals_cluster");if(context.activeVenues>=15)flags.push("busy_15venues");if(context.activeVenues<=10)flags.push("light_10venues");if(context.minute<720)flags.push("morning_before12");if(context.minute>=1020)flags.push("evening_after17");if([0,5].includes(context.minute%10))flags.push("minute_0or5_placebo");if(context.minute%10===7)flags.push("minute_7_placebo");evalRows.push({period:row.date<="2024-12-31"?"discovery":"forward",date:row.date,venue:program.venue,raceNo:program.race_no,selection:row.combination,implied:(1/row.odds)/(overround.get(row.race_id)??1),hit:row.winner===row.combination,payout:row.payout_yen??0,flags});}
  const cells=factors.flatMap(([id,label,group])=>selections.map(selection=>({id,label,group,selection,discovery:metric(evalRows.filter(r=>r.period==="discovery"&&r.selection===selection&&r.flags.includes(id))),forward:metric(evalRows.filter(r=>r.period==="forward"&&r.selection===selection&&r.flags.includes(id)))})));const eligible=cells.filter(c=>c.discovery.n>=30&&c.forward.n>=30);const stable=eligible.filter(c=>c.discovery.edgePp>0&&c.forward.edgePp>0).sort((a,b)=>Math.min(b.discovery.edgePp,b.forward.edgePp)-Math.min(a.discovery.edgePp,a.forward.edgePp));const robust=stable.filter(c=>c.discovery.max2HitExclRoi>=1&&c.forward.max2HitExclRoi>=1);const placebo=eligible.filter(c=>c.group==="placebo");
  const matched=eligible.filter(c=>c.group!=="placebo").map(c=>{const discovery=matchedResidual(evalRows.filter(r=>r.period==="discovery"&&r.selection===c.selection),c.id),forward=matchedResidual(evalRows.filter(r=>r.period==="forward"&&r.selection===c.selection),c.id);return{id:c.id,label:c.label,selection:c.selection,discovery,forward,leaveOneVenue:{discovery:leaveOneVenue(evalRows.filter(r=>r.period==="discovery"&&r.selection===c.selection),c.id),forward:leaveOneVenue(evalRows.filter(r=>r.period==="forward"&&r.selection===c.selection),c.id)}};}).filter(c=>c.discovery.matched>=30&&c.forward.matched>=30).sort((a,b)=>Math.min(b.discovery.deltaPp,b.forward.deltaPp)-Math.min(a.discovery.deltaPp,a.forward.deltaPp));const matchedPositive=matched.filter(c=>c.discovery.deltaPp>0&&c.forward.deltaPp>0);
  const report={generatedAt:new Date().toISOString(),safety:{readOnly:true,preRaceSchedule:true,productionConnected:false},coverage:{programRows:programs.length,validProgramRows:validPrograms.length,exactaRacesWithValidSchedule:scheduledRaces,evaluatedRows:evalRows.length},family:{factors:factors.length,selections:selections.length,cells:cells.length,eligible:eligible.length},stable,robust,placebo,matched,matchedPositive,caveats:["公式番組の締切予定時刻を使用","1〜12R完備・時刻単調増加venue-dayだけ採用","matched比較は会場×R番号×暦月を固定","時刻帯と開催場には未観測交絡が残る","closing oddsでT-5ではない","末尾分は偽陽性対照"]};mkdirSync("reports",{recursive:true});writeFileSync("reports/market-attention-screen.json",`${JSON.stringify(report,null,2)}\n`);
  const lines=["# 投票者attention分散×exacta市場残差","","> 他場締切の近接・同日開催負荷を調べるread-only探索。closing oddsでありT-5ではない。","",`schedule coverage: 全${programs.length}行 / 品質gate後${validPrograms.length}行 / exacta評価${scheduledRaces}レース`,`探索族: ${factors.length}因子×${selections.length}買い目=${cells.length}セル（両期n≥30: ${eligible.length}）`,"","## 2024・2025とも市場残差プラス","","| 順位 | attention proxy | 買い目 | 2024 n / edge / ROI / max2 | 2025 n / edge / ROI / max2 |","|---:|---|---:|---:|---:|",...stable.map((c,i)=>`| ${i+1} | ${c.label} | ${c.selection} | ${cell(c.discovery)} | ${cell(c.forward)} |`),"","最大2的中除外まで両期100%以上:","",robust.length?robust.map(c=>`- ${c.label} × ${c.selection}`).join("\n"):"該当なし。","","## 会場×R番号×暦月を揃えた残差差","","> 同じstratum内で条件ありと条件なしを比較。deltaがプラスなら条件側に追加残差。leave-one会場最小値がマイナスなら特定場依存を崩せない。","","| attention proxy | 買い目 | 2024 matched / coverage / delta / LOO最小 | 2025 matched / coverage / delta / LOO最小 |","|---|---:|---:|---:|",...matchedPositive.map(c=>`| ${c.label} | ${c.selection} | ${matchedCell(c.discovery)} / ${signed(c.leaveOneVenue.discovery)}pt | ${matchedCell(c.forward)} / ${signed(c.leaveOneVenue.forward)}pt |`),"",`両期deltaプラス: ${matchedPositive.length}セル。両期leave-one会場最小deltaもプラス: ${matchedPositive.filter(c=>c.leaveOneVenue.discovery>0&&c.leaveOneVenue.forward>0).length}セル。`,"","## placebo","","| placebo | 買い目 | 2024 n / edge / ROI | 2025 n / edge / ROI |","|---|---:|---:|---:|",...placebo.map(c=>`| ${c.label} | ${c.selection} | ${short(c.discovery)} | ${short(c.forward)} |`),"","## 判定","","- 締切衝突は注意分散のproxyで、売上・投票人数を直接観測していない。","- 時刻帯・場・季節を揃えた再検証とfuture T-5再現前にBUYへ接続しない。"] ;writeFileSync("reports/market-attention-screen.md",`${lines.join("\n")}\n`);console.log(`market attention: scheduled=${scheduledRaces} eligible=${eligible.length} stable=${stable.length} robust=${robust.length} matchedPositive=${matchedPositive.length}`);
}finally{db.close();}
function schedule(r:ProgramRow):ScheduledRace{return{raceId:r.race_id,venue:r.venue,raceNo:r.race_no,closeAt:r.close_at};}function metric(rows:EvalRow[]):Metric{const payouts=rows.filter(r=>r.hit).map(r=>r.payout).sort((a,b)=>b-a),total=payouts.reduce((a,b)=>a+b,0),expected=rows.reduce((s,r)=>s+r.implied,0);return{n:rows.length,hits:payouts.length,edgePp:rows.length?(payouts.length-expected)/rows.length*100:0,roi:rows.length?total/(rows.length*100):0,max2HitExclRoi:rows.length>2?(total-(payouts[0]??0)-(payouts[1]??0))/((rows.length-2)*100):0};}function pct(v:number){return`${(v*100).toFixed(1)}%`;}function cell(v:Metric){return`${v.n} / ${v.edgePp>=0?"+":""}${v.edgePp.toFixed(2)}pt / ${pct(v.roi)} / ${pct(v.max2HitExclRoi)}`;}function short(v:Metric){return`${v.n} / ${v.edgePp>=0?"+":""}${v.edgePp.toFixed(2)}pt / ${pct(v.roi)}`;}
function matchedResidual(rows:EvalRow[],flag:string){const controls=new Map<string,EvalRow[]>();for(const row of rows.filter(r=>!r.flags.includes(flag))){const key=stratum(row);controls.set(key,[...(controls.get(key)??[]),row]);}const treated=rows.filter(r=>r.flags.includes(flag));let matched=0,treatedResidual=0,controlResidual=0;for(const row of treated){const peers=controls.get(stratum(row));if(!peers?.length)continue;matched++;treatedResidual+=residual(row);controlResidual+=peers.reduce((s,p)=>s+residual(p),0)/peers.length;}return{treated:treated.length,matched,coverage:treated.length?matched/treated.length:0,deltaPp:matched?(treatedResidual-controlResidual)/matched*100:0};}function leaveOneVenue(rows:EvalRow[],flag:string){const values=[...new Set(rows.map(r=>r.venue))].map(venue=>matchedResidual(rows.filter(r=>r.venue!==venue),flag)).filter(r=>r.matched>=30).map(r=>r.deltaPp);return values.length?Math.min(...values):0;}function residual(row:EvalRow){return(row.hit?1:0)-row.implied;}function stratum(row:EvalRow){return`${row.venue}|${row.raceNo}|${row.date.slice(5,7)}`;}function signed(v:number){return`${v>=0?"+":""}${v.toFixed(2)}`;}function matchedCell(v:{matched:number;coverage:number;deltaPp:number}){return`${v.matched} / ${pct(v.coverage)} / ${signed(v.deltaPp)}pt`;}
