/**
 * 6月だけでT-5市場残差モデルを学習し、7月を完全forward評価する。
 * モデルは市場温度較正と買い目別残差の縮約だけ。外部特徴量は使わない。
 * 読み取り専用。本番判定・DB・app_settingsは変更しない。
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import { evaluateProbabilityModel, fitSelectionResidual, fitTemperature, marketModel, selectionResidualModel, temperatureModel, type ResidualRace } from "../src/domain/t5ResidualModel";

const DB_PATH=process.env.BOAT_PON_DB_PATH??"data/boat.sqlite";
const FROM=process.env.BOAT_PON_FROM??"2026-06-01";
const TO=process.env.BOAT_PON_TO??todayJst();
const BOUNDARY=process.env.BOAT_PON_BOUNDARY??"2026-07-01";
const OUT_MD="reports/t5-residual-forward.md",OUT_JSON="reports/t5-residual-forward.json";
if(!existsSync(DB_PATH))throw new Error(`DB not found: ${DB_PATH}`);
const db=new DatabaseSync(DB_PATH,{readOnly:true});db.exec("PRAGMA query_only=ON; PRAGMA busy_timeout=30000;");
type O={id:number;race_id:string;selection:string;odds:number}; type R={race_id:string;date:string;venue:string;race_no:number;trifecta:string|null;payout_yen:number|null;returned:number};
const fromId=FROM.replaceAll("-","");const toId=addDays(TO,1).replaceAll("-","");
const odds=db.prepare(`WITH complete_capture AS(SELECT race_id,captured_at,MAX(id)max_id FROM odds_timeseries_snapshots WHERE race_id>=? AND race_id<? AND checkpoint_label='T-5' GROUP BY race_id,captured_at HAVING COUNT(DISTINCT selection)=120),latest_capture AS(SELECT race_id,MAX(max_id)max_id FROM complete_capture GROUP BY race_id),chosen AS(SELECT c.race_id,c.captured_at FROM complete_capture c JOIN latest_capture l ON l.race_id=c.race_id AND l.max_id=c.max_id) SELECT id,race_id,selection,odds FROM odds_timeseries_snapshots WHERE id IN(SELECT MAX(o.id) FROM odds_timeseries_snapshots o JOIN chosen c ON c.race_id=o.race_id AND c.captured_at=o.captured_at GROUP BY o.race_id,o.selection)`).all(fromId,toId)as O[];
const results=db.prepare(`SELECT race_id,date,venue,race_no,trifecta,payout_yen,returned FROM race_results WHERE date>=? AND date<=?`).all(FROM,TO)as R[];db.close();
const byRace=new Map<string,O[]>();for(const o of odds)byRace.set(o.race_id,[...(byRace.get(o.race_id)??[]),o]);const resultMap=new Map(results.map(r=>[r.race_id,r]));const races:ResidualRace[]=[];
for(const [raceId,source] of byRace){const unique=new Map(source.map(x=>[x.selection,x]));const result=resultMap.get(raceId);if(unique.size!==120||!result?.trifecta||result.returned||result.payout_yen==null)continue;const rows=[...unique.values()];if(rows.some(x=>x.odds<=1||!Number.isFinite(x.odds)))continue;const overround=rows.reduce((s,x)=>s+1/x.odds,0);if(!(overround>0)||!unique.has(result.trifecta))continue;races.push({raceId,date:result.date,venue:result.venue,raceNo:result.race_no,winner:result.trifecta,payoutYen:result.payout_yen,outcomes:rows.map(x=>({selection:x.selection,odds:x.odds,marketProbability:(1/x.odds)/overround}))});}
races.sort((a,b)=>a.date.localeCompare(b.date)||a.raceId.localeCompare(b.raceId));const train=races.filter(r=>r.date<BOUNDARY),forward=races.filter(r=>r.date>=BOUNDARY);
const fittedTemperature=fitTemperature(train);const fittedResidual=fitSelectionResidual(train);const temperature=temperatureModel(fittedTemperature.temperature);const residual=selectionResidualModel(fittedResidual.factors,fittedResidual.temperature);
const variants=[{id:"market",label:"T-5市場",model:marketModel},{id:"temperature",label:`市場temperature T=${fittedTemperature.temperature}`,model:temperature},{id:"selection-residual",label:`買い目残差 T=${fittedResidual.temperature} prior=${fittedResidual.priorStrength}`,model:residual}];
const metrics=variants.map(v=>({id:v.id,label:v.label,train:evaluateProbabilityModel(train,v.model),forward:evaluateProbabilityModel(forward,v.model)}));const marketForward=metrics.find(x=>x.id==="market")!.forward;const residualForward=metrics.find(x=>x.id==="selection-residual")!.forward;
const venues=[...new Set(forward.map(r=>r.venue))].sort().map(venue=>{const venueTrain=train.filter(r=>r.venue!==venue);const venueForward=forward.filter(r=>r.venue===venue);const fit=fitSelectionResidual(venueTrain);const model=selectionResidualModel(fit.factors,fit.temperature);const market=evaluateProbabilityModel(venueForward,marketModel);const candidate=evaluateProbabilityModel(venueForward,model);return{venue,n:venueForward.length,temperature:fit.temperature,priorStrength:fit.priorStrength,market,candidate,logLossDelta:candidate.logLoss!=null&&market.logLoss!=null?candidate.logLoss-market.logLoss:null,brierDelta:candidate.brier!=null&&market.brier!=null?candidate.brier-market.brier:null};});
const gate={minimumForward:300,targetForward:1000,checks:{sample:forward.length>=300,logLoss:residualForward.logLoss!=null&&marketForward.logLoss!=null&&residualForward.logLoss<marketForward.logLoss,brier:residualForward.brier!=null&&marketForward.brier!=null&&residualForward.brier<marketForward.brier,payoutRoi:(residualForward.payoutRoi??0)>=1,payoutRoiExTop2:(residualForward.payoutRoiExTop2??0)>=1,venueLoo:venues.filter(v=>v.n>=3).every(v=>(v.logLossDelta??Infinity)<=0)},passed:false};gate.passed=Object.values(gate.checks).every(Boolean)&&forward.length>=1000;
const report={generatedAt:new Date().toISOString(),safety:{readOnly:true,dbWrites:false,productionChanged:false,pointInTime:"T-5 market only"},window:{from:FROM,to:TO,boundary:BOUNDARY},coverage:{races:races.length,train:train.length,forward:forward.length},fit:{temperature:fittedTemperature.temperature,residual:{temperature:fittedResidual.temperature,priorStrength:fittedResidual.priorStrength}},metrics,venueLoo:venues,gate,caveats:["ハイパーパラメータは6月trainだけで選択","7月forwardを再学習・条件探索へ戻していない","外部特徴量なし。買い目残差は構造的偏りの最小仮説","n<1000のため最終改善判定はBLOCKED"]};
const p=(v:number|null)=>v==null?"-":`${(v*100).toFixed(2)}%`,n=(v:number|null)=>v==null?"-":v.toFixed(4),d=(v:number|null)=>v==null?"-":`${v>=0?"+":""}${v.toFixed(4)}`;
const lines=["# T-5市場残差 forward評価", "", `生成日時: ${report.generatedAt}`, "", "> 6月だけで学習し、7月は完全forward。単一captured_atの完全市場だけを使用。読み取り専用・本番未接続。", "", `- 完全市場: ${races.length} / train: ${train.length} / forward: ${forward.length}`, `- 選択パラメータ: temperature=${fittedResidual.temperature}, prior=${fittedResidual.priorStrength}`, "", "## 同一race_id比較", "", "| モデル | train logloss / Brier / ROI / exTop2 | forward logloss / Brier / ROI / exTop2 |", "|---|---:|---:|", ...metrics.map(x=>`| ${x.label} | ${n(x.train.logLoss)} / ${n(x.train.brier)} / ${p(x.train.payoutRoi)} / ${p(x.train.payoutRoiExTop2)} | ${n(x.forward.logLoss)} / ${n(x.forward.brier)} / ${p(x.forward.payoutRoi)} / ${p(x.forward.payoutRoiExTop2)} |`), "", "## 会場LOO", "", "| 会場 | forward n | logloss差(残差-市場) | Brier差 | 市場ROI | 残差ROI |", "|---|---:|---:|---:|---:|---:|", ...venues.map(v=>`| ${v.venue} | ${v.n} | ${d(v.logLossDelta)} | ${d(v.brierDelta)} | ${p(v.market.payoutRoi)} | ${p(v.candidate.payoutRoi)} |`), "", "## 昇格gate", "", ...Object.entries(gate.checks).map(([key,value])=>`- ${value?"✅":"❌"} ${key}`), `- 最終判定: **${gate.passed?"PASS":"BLOCKED"}**（forward ${forward.length}/${gate.targetForward}）`, "", "## 結論", "", "- logloss/Brierと実払戻ROIを同時に市場より改善し、会場LOOと1,000件gateを通るまで本番へ接続しない。", "- 現在の結果が不合格なら、買い目残差だけでは予測改善にならない。次の特徴量を追加する前にこの失敗を固定する。"];
mkdirSync("reports",{recursive:true});writeFileSync(OUT_JSON,`${JSON.stringify(report,null,2)}\n`);writeFileSync(OUT_MD,`${lines.join("\n")}\n`);console.log(`[t5-residual-forward] wrote ${OUT_MD} / ${OUT_JSON}`);
function addDays(date:string,delta:number){const d=new Date(`${date}T00:00:00+09:00`);d.setUTCDate(d.getUTCDate()+delta);return d.toLocaleDateString("en-CA",{timeZone:"Asia/Tokyo"});}
function todayJst(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo"}).format(new Date());}
